name: outdoor_navigation
description: Applicazione per la navigazione outdoor con supporto per trekking, ciclismo, e-bike e corsa.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.0.0
  supabase_flutter: ^2.0.1  # Tenere solo la versione più recente
  
  # Gestione stato
  provider: ^6.1.1
  flutter_bloc: ^8.1.3

  # UI
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  shimmer: ^3.0.0
  
  # Navigazione
  go_router: ^12.1.3
  uni_links: ^0.5.1  # Per il deep linking con Supabase
  
  # Networking
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  
  # Persistenza
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Mappe e localizzazione
  flutter_map: ^6.2.1  # Compatibile con http 1.0.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  
  # Utility
  intl: ^0.19.0
  timeago: ^3.6.0
  logger: ^2.0.2
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  image_picker: ^1.0.5
  path_provider: ^2.1.1
  flutter_local_notifications: ^16.2.0
  permission_handler: ^11.1.0
  battery_plus: ^4.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
